# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QLayout, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QVBoxLayout, QWidget)
import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1299, 719)
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"\n"
"  background: #232526; /* fallback for old browsers */\n"
"  background: -webkit-linear-gradient(to right, #232526, #414345); /* Chrome 10-25, Safari 5.1-6 */\n"
"  background: linear-gradient(to right, #232526, #414345); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setLayoutDirection(Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet(u"background: url(:/images/images/background.png);\n"
"border-radius: 10px;")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(1190, 10, 91, 41))
        self.control_buttons = QHBoxLayout(self.layoutWidget)
        self.control_buttons.setObjectName(u"control_buttons")
        self.control_buttons.setContentsMargins(0, 0, 0, 0)
        self.wrap_button = QPushButton(self.layoutWidget)
        self.wrap_button.setObjectName(u"wrap_button")
        self.wrap_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon = QIcon()
        icon.addFile(u":/images/images/wrap_btn.png", QSize(), QIcon.Normal, QIcon.Off)
        self.wrap_button.setIcon(icon)
        self.wrap_button.setIconSize(QSize(32, 32))

        self.control_buttons.addWidget(self.wrap_button)

        self.close_button = QPushButton(self.layoutWidget)
        self.close_button.setObjectName(u"close_button")
        self.close_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u":/images/images/exit_btn.png", QSize(), QIcon.Normal, QIcon.Off)
        self.close_button.setIcon(icon1)
        self.close_button.setIconSize(QSize(32, 32))

        self.control_buttons.addWidget(self.close_button)

        self.start_button = QPushButton(self.centralwidget)
        self.start_button.setObjectName(u"start_button")
        self.start_button.setGeometry(QRect(1029, 640, 211, 50))
        self.start_button.setMinimumSize(QSize(200, 50))
        font1 = QFont()
        font1.setFamilies([u"Gotham Pro Black"])
        font1.setPointSize(14)
        font1.setBold(False)
        self.start_button.setFont(font1)
        self.start_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.start_button.setStyleSheet(u"background: rgb(255,170,32);\n"
"border-radius: 5px;")
        self.start_button.setAutoDefault(False)
        self.wrap_button_2 = QPushButton(self.centralwidget)
        self.wrap_button_2.setObjectName(u"wrap_button_2")
        self.wrap_button_2.setGeometry(QRect(10, 10, 42, 32))
        icon2 = QIcon()
        icon2.addFile(u":/images/images/menu_button.png", QSize(), QIcon.Normal, QIcon.Off)
        self.wrap_button_2.setIcon(icon2)
        self.wrap_button_2.setIconSize(QSize(32, 32))
        self.wrap_button_3 = QPushButton(self.centralwidget)
        self.wrap_button_3.setObjectName(u"wrap_button_3")
        self.wrap_button_3.setGeometry(QRect(10, 50, 42, 32))
        icon3 = QIcon()
        icon3.addFile(u":/images/images/settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.wrap_button_3.setIcon(icon3)
        self.wrap_button_3.setIconSize(QSize(32, 32))
        self.menu = QFrame(self.centralwidget)
        self.menu.setObjectName(u"menu")
        self.menu.setGeometry(QRect(40, 220, 341, 451))
        self.menu.setStyleSheet(u"background: rgba(0,0,0,0)")
        self.menu.setFrameShape(QFrame.StyledPanel)
        self.menu.setFrameShadow(QFrame.Raised)
        self.item_messages = QPushButton(self.menu)
        self.item_messages.setObjectName(u"item_messages")
        self.item_messages.setGeometry(QRect(0, 20, 340, 75))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.item_messages.sizePolicy().hasHeightForWidth())
        self.item_messages.setSizePolicy(sizePolicy)
        self.item_messages.setMinimumSize(QSize(340, 75))
        self.item_messages.setMaximumSize(QSize(340, 75))
        font2 = QFont()
        font2.setFamilies([u"Gotham Pro Black"])
        font2.setPointSize(18)
        font2.setStyleStrategy(QFont.PreferDefault)
        self.item_messages.setFont(font2)
        self.item_messages.setCursor(QCursor(Qt.PointingHandCursor))
        self.item_messages.setMouseTracking(False)
        self.item_messages.setTabletTracking(False)
        self.item_messages.setFocusPolicy(Qt.StrongFocus)
        self.item_messages.setAcceptDrops(False)
        self.item_messages.setStyleSheet(u"background: none;\n"
"color: white;\n"
"text-align: left;")
        icon4 = QIcon()
        icon4.addFile(u":/images/images/messages.png", QSize(), QIcon.Normal, QIcon.Off)
        self.item_messages.setIcon(icon4)
        self.item_messages.setIconSize(QSize(128, 128))
        self.item_accounts = QPushButton(self.menu)
        self.item_accounts.setObjectName(u"item_accounts")
        self.item_accounts.setGeometry(QRect(0, 90, 340, 75))
        sizePolicy.setHeightForWidth(self.item_accounts.sizePolicy().hasHeightForWidth())
        self.item_accounts.setSizePolicy(sizePolicy)
        self.item_accounts.setMinimumSize(QSize(340, 75))
        self.item_accounts.setMaximumSize(QSize(340, 75))
        self.item_accounts.setFont(font2)
        self.item_accounts.setCursor(QCursor(Qt.PointingHandCursor))
        self.item_accounts.setMouseTracking(False)
        self.item_accounts.setTabletTracking(False)
        self.item_accounts.setFocusPolicy(Qt.StrongFocus)
        self.item_accounts.setAcceptDrops(False)
        self.item_accounts.setStyleSheet(u"background: none;\n"
"color: white;\n"
"text-align: left;")
        icon5 = QIcon()
        icon5.addFile(u":/images/images/all_accounts.png", QSize(), QIcon.Normal, QIcon.Off)
        self.item_accounts.setIcon(icon5)
        self.item_accounts.setIconSize(QSize(128, 128))
        self.item_calendar = QPushButton(self.menu)
        self.item_calendar.setObjectName(u"item_calendar")
        self.item_calendar.setGeometry(QRect(0, 160, 340, 75))
        sizePolicy.setHeightForWidth(self.item_calendar.sizePolicy().hasHeightForWidth())
        self.item_calendar.setSizePolicy(sizePolicy)
        self.item_calendar.setMinimumSize(QSize(340, 75))
        self.item_calendar.setMaximumSize(QSize(340, 75))
        self.item_calendar.setFont(font2)
        self.item_calendar.setCursor(QCursor(Qt.PointingHandCursor))
        self.item_calendar.setMouseTracking(False)
        self.item_calendar.setTabletTracking(False)
        self.item_calendar.setFocusPolicy(Qt.StrongFocus)
        self.item_calendar.setAcceptDrops(False)
        self.item_calendar.setStyleSheet(u"background: none;\n"
"color: white;\n"
"text-align: left;")
        icon6 = QIcon()
        icon6.addFile(u":/images/images/calendar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.item_calendar.setIcon(icon6)
        self.item_calendar.setIconSize(QSize(128, 128))
        self.item_shop = QPushButton(self.menu)
        self.item_shop.setObjectName(u"item_shop")
        self.item_shop.setGeometry(QRect(0, 230, 340, 75))
        sizePolicy.setHeightForWidth(self.item_shop.sizePolicy().hasHeightForWidth())
        self.item_shop.setSizePolicy(sizePolicy)
        self.item_shop.setMinimumSize(QSize(340, 75))
        self.item_shop.setMaximumSize(QSize(340, 75))
        self.item_shop.setFont(font2)
        self.item_shop.setCursor(QCursor(Qt.PointingHandCursor))
        self.item_shop.setMouseTracking(False)
        self.item_shop.setTabletTracking(False)
        self.item_shop.setFocusPolicy(Qt.StrongFocus)
        self.item_shop.setAcceptDrops(False)
        self.item_shop.setStyleSheet(u"background: none;\n"
"color: white;\n"
"text-align: left;")
        icon7 = QIcon()
        icon7.addFile(u":/images/images/shop.png", QSize(), QIcon.Normal, QIcon.Off)
        self.item_shop.setIcon(icon7)
        self.item_shop.setIconSize(QSize(128, 128))
        self.item_points = QPushButton(self.menu)
        self.item_points.setObjectName(u"item_points")
        self.item_points.setGeometry(QRect(0, 300, 340, 75))
        sizePolicy.setHeightForWidth(self.item_points.sizePolicy().hasHeightForWidth())
        self.item_points.setSizePolicy(sizePolicy)
        self.item_points.setMinimumSize(QSize(340, 75))
        self.item_points.setMaximumSize(QSize(340, 75))
        self.item_points.setFont(font2)
        self.item_points.setCursor(QCursor(Qt.PointingHandCursor))
        self.item_points.setMouseTracking(False)
        self.item_points.setTabletTracking(False)
        self.item_points.setFocusPolicy(Qt.StrongFocus)
        self.item_points.setAcceptDrops(False)
        self.item_points.setStyleSheet(u"background: none;\n"
"color: white;\n"
"text-align: left;")
        icon8 = QIcon()
        icon8.addFile(u":/images/images/diamond.png", QSize(), QIcon.Normal, QIcon.Off)
        self.item_points.setIcon(icon8)
        self.item_points.setIconSize(QSize(128, 128))
        self.item_devices = QPushButton(self.menu)
        self.item_devices.setObjectName(u"item_devices")
        self.item_devices.setGeometry(QRect(0, 370, 340, 75))
        sizePolicy.setHeightForWidth(self.item_devices.sizePolicy().hasHeightForWidth())
        self.item_devices.setSizePolicy(sizePolicy)
        self.item_devices.setMinimumSize(QSize(340, 75))
        self.item_devices.setMaximumSize(QSize(340, 75))
        self.item_devices.setFont(font2)
        self.item_devices.setCursor(QCursor(Qt.PointingHandCursor))
        self.item_devices.setMouseTracking(False)
        self.item_devices.setTabletTracking(False)
        self.item_devices.setFocusPolicy(Qt.StrongFocus)
        self.item_devices.setAcceptDrops(False)
        self.item_devices.setStyleSheet(u"background: none;\n"
"color: white;\n"
"text-align: left;")
        icon9 = QIcon()
        icon9.addFile(u":/images/images/monitor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.item_devices.setIcon(icon9)
        self.item_devices.setIconSize(QSize(128, 128))
        self.hyus_icon = QLabel(self.centralwidget)
        self.hyus_icon.setObjectName(u"hyus_icon")
        self.hyus_icon.setGeometry(QRect(1140, 560, 61, 61))
        self.hyus_icon.setCursor(QCursor(Qt.PointingHandCursor))
        self.hyus_icon.setStyleSheet(u"background: url(:/images/images/hyus.png);\n"
"border-radius: 10px;")
        self.hyus_icon.setScaledContents(True)
        self.pkle_border = QLabel(self.centralwidget)
        self.pkle_border.setObjectName(u"pkle_border")
        self.pkle_border.setGeometry(QRect(1210, 560, 61, 61))
        self.pkle_border.setCursor(QCursor(Qt.PointingHandCursor))
        self.pkle_border.setStyleSheet(u"background: rgba(0,0,0,0);\n"
"border: 1px solid rgb(3,249,60)")
        self.pkle_border.setScaledContents(True)
        self.hyus_border = QLabel(self.centralwidget)
        self.hyus_border.setObjectName(u"hyus_border")
        self.hyus_border.setGeometry(QRect(1140, 560, 61, 61))
        self.hyus_border.setCursor(QCursor(Qt.PointingHandCursor))
        self.hyus_border.setStyleSheet(u"background: rgba(0,0,0,0);\n"
"border: 1px solid rgb(206,18,208)")
        self.hyus_border.setScaledContents(True)
        self.ibby_icon = QLabel(self.centralwidget)
        self.ibby_icon.setObjectName(u"ibby_icon")
        self.ibby_icon.setGeometry(QRect(1070, 560, 61, 61))
        self.ibby_icon.setCursor(QCursor(Qt.PointingHandCursor))
        self.ibby_icon.setStyleSheet(u"background: url(:/images/images/ibby.png);\n"
"border-radius: 10px;")
        self.ibby_icon.setScaledContents(True)
        self.ibby_border = QLabel(self.centralwidget)
        self.ibby_border.setObjectName(u"ibby_border")
        self.ibby_border.setGeometry(QRect(1070, 560, 61, 61))
        self.ibby_border.setCursor(QCursor(Qt.PointingHandCursor))
        self.ibby_border.setStyleSheet(u"background: rgba(0,0,0,0);\n"
"border: 1px solid rgb(66,0,255)")
        self.ibby_border.setScaledContents(True)
        self.pkle_icon = QLabel(self.centralwidget)
        self.pkle_icon.setObjectName(u"pkle_icon")
        self.pkle_icon.setGeometry(QRect(1210, 560, 61, 61))
        self.pkle_icon.setCursor(QCursor(Qt.PointingHandCursor))
        self.pkle_icon.setStyleSheet(u"background: url(:/images/images/pkle.png);\n"
"border-radius: 10px;")
        self.pkle_icon.setScaledContents(True)
        self.wrewards_border = QLabel(self.centralwidget)
        self.wrewards_border.setObjectName(u"wrewards_border")
        self.wrewards_border.setGeometry(QRect(1000, 560, 61, 61))
        self.wrewards_border.setCursor(QCursor(Qt.PointingHandCursor))
        self.wrewards_border.setStyleSheet(u"background: rgba(0,0,0,0);\n"
"border: 1px solid rgb(2,196,252)")
        self.wrewards_border.setScaledContents(True)
        self.wrewards_icon = QLabel(self.centralwidget)
        self.wrewards_icon.setObjectName(u"wrewards_icon")
        self.wrewards_icon.setGeometry(QRect(1000, 560, 61, 61))
        self.wrewards_icon.setCursor(QCursor(Qt.PointingHandCursor))
        self.wrewards_icon.setStyleSheet(u"background: url(:/images/images/wrewards.png);\n"
"border-radius: 10px;")
        self.wrewards_icon.setScaledContents(True)
        self.start_button_error_text = QLabel(self.centralwidget)
        self.start_button_error_text.setObjectName(u"start_button_error_text")
        self.start_button_error_text.setGeometry(QRect(1050, 520, 171, 41))
        font3 = QFont()
        font3.setFamilies([u"Gotham Pro"])
        font3.setPointSize(12)
        self.start_button_error_text.setFont(font3)
        self.start_button_error_text.setStyleSheet(u"color: rgb(255,170,32);\n"
"background: none")
        self.login_error_text = QLabel(self.centralwidget)
        self.login_error_text.setObjectName(u"login_error_text")
        self.login_error_text.setEnabled(True)
        self.login_error_text.setGeometry(QRect(500, 570, 282, 44))
        font4 = QFont()
        font4.setFamilies([u"Gotham Pro"])
        font4.setPointSize(12)
        font4.setItalic(False)
        self.login_error_text.setFont(font4)
        self.login_error_text.setMouseTracking(False)
        self.login_error_text.setLayoutDirection(Qt.LeftToRight)
        self.login_error_text.setAutoFillBackground(False)
        self.login_error_text.setStyleSheet(u"background: rgba(0,0,0,0);\n"
"color: #ffae00;")
        self.login_error_text.setFrameShadow(QFrame.Plain)
        self.login_error_text.setScaledContents(False)
        self.login_error_text.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.login_error_text.setWordWrap(False)
        self.login_frame = QFrame(self.centralwidget)
        self.login_frame.setObjectName(u"login_frame")
        self.login_frame.setGeometry(QRect(490, 200, 300, 360))
        self.login_frame.setLayoutDirection(Qt.LeftToRight)
        self.login_frame.setAutoFillBackground(False)
        self.login_frame.setStyleSheet(u"background: rgb(255,170,32);\n"
"border-radius: 3px;")
        self.login_frame.setFrameShape(QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.login_frame)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.login_label_title = QLabel(self.login_frame)
        self.login_label_title.setObjectName(u"login_label_title")
        self.login_label_title.setMaximumSize(QSize(16777215, 50))
        font5 = QFont()
        font5.setFamilies([u"Gotham Pro Black"])
        font5.setPointSize(24)
        self.login_label_title.setFont(font5)
        self.login_label_title.setLayoutDirection(Qt.LeftToRight)
        self.login_label_title.setTextFormat(Qt.AutoText)
        self.login_label_title.setScaledContents(False)
        self.login_label_title.setAlignment(Qt.AlignCenter)
        self.login_label_title.setWordWrap(False)
        self.login_label_title.setMargin(2)
        self.login_label_title.setIndent(-1)
        self.login_label_title.setTextInteractionFlags(Qt.TextEditable)

        self.verticalLayout_3.addWidget(self.login_label_title)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.pass_icon_2 = QLabel(self.login_frame)
        self.pass_icon_2.setObjectName(u"pass_icon_2")
        self.pass_icon_2.setMaximumSize(QSize(30, 30))
        self.pass_icon_2.setPixmap(QPixmap(u":/images/images/id-card.svg"))
        self.pass_icon_2.setScaledContents(True)

        self.horizontalLayout_3.addWidget(self.pass_icon_2)

        self.login_title = QLabel(self.login_frame)
        self.login_title.setObjectName(u"login_title")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.login_title.sizePolicy().hasHeightForWidth())
        self.login_title.setSizePolicy(sizePolicy1)
        self.login_title.setMinimumSize(QSize(300, 10))
        self.login_title.setMaximumSize(QSize(100, 30))
        font6 = QFont()
        font6.setFamilies([u"Gotham Pro Black"])
        font6.setPointSize(16)
        font6.setUnderline(False)
        font6.setStrikeOut(False)
        self.login_title.setFont(font6)
        self.login_title.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.login_title.setLayoutDirection(Qt.LeftToRight)
        self.login_title.setAutoFillBackground(False)

        self.horizontalLayout_3.addWidget(self.login_title)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.login_input = QLineEdit(self.login_frame)
        self.login_input.setObjectName(u"login_input")
        self.login_input.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.login_input.sizePolicy().hasHeightForWidth())
        self.login_input.setSizePolicy(sizePolicy2)
        self.login_input.setMinimumSize(QSize(10, 35))
        self.login_input.setMaximumSize(QSize(16777215, 16777215))
        self.login_input.setFont(font3)
        self.login_input.setCursor(QCursor(Qt.IBeamCursor))
        self.login_input.setStyleSheet(u"background: rgba(0,0, 0,35)")

        self.verticalLayout_2.addWidget(self.login_input)


        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.pass_icon = QLabel(self.login_frame)
        self.pass_icon.setObjectName(u"pass_icon")
        self.pass_icon.setMaximumSize(QSize(30, 30))
        self.pass_icon.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.pass_icon.setPixmap(QPixmap(u":/images/images/bank.svg"))
        self.pass_icon.setScaledContents(True)
        self.pass_icon.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.horizontalLayout_2.addWidget(self.pass_icon)

        self.pass_title = QLabel(self.login_frame)
        self.pass_title.setObjectName(u"pass_title")
        self.pass_title.setMaximumSize(QSize(300, 30))
        font7 = QFont()
        font7.setFamilies([u"Gotham Pro Black"])
        font7.setPointSize(16)
        font7.setBold(False)
        font7.setItalic(False)
        self.pass_title.setFont(font7)

        self.horizontalLayout_2.addWidget(self.pass_title)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.pass_input = QLineEdit(self.login_frame)
        self.pass_input.setObjectName(u"pass_input")
        sizePolicy2.setHeightForWidth(self.pass_input.sizePolicy().hasHeightForWidth())
        self.pass_input.setSizePolicy(sizePolicy2)
        self.pass_input.setMinimumSize(QSize(10, 35))
        self.pass_input.setSizeIncrement(QSize(0, 0))
        self.pass_input.setStyleSheet(u"background: rgba(0,0, 0,35)")
        self.pass_input.setFrame(True)

        self.verticalLayout.addWidget(self.pass_input)


        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.forgot_pass = QLabel(self.login_frame)
        self.forgot_pass.setObjectName(u"forgot_pass")
        self.forgot_pass.setMinimumSize(QSize(0, 20))
        self.forgot_pass.setMaximumSize(QSize(150, 20))
        font8 = QFont()
        font8.setFamilies([u"Gotham Pro Light"])
        font8.setPointSize(11)
        font8.setUnderline(True)
        self.forgot_pass.setFont(font8)
        self.forgot_pass.setCursor(QCursor(Qt.PointingHandCursor))
        self.forgot_pass.setFocusPolicy(Qt.NoFocus)
        self.forgot_pass.setLayoutDirection(Qt.RightToLeft)
        self.forgot_pass.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.forgot_pass.setMargin(0)

        self.verticalLayout_3.addWidget(self.forgot_pass)

        self.label_space = QLabel(self.login_frame)
        self.label_space.setObjectName(u"label_space")
        self.label_space.setMaximumSize(QSize(16777215, 30))

        self.verticalLayout_3.addWidget(self.label_space)

        self.login_button = QPushButton(self.login_frame)
        self.login_button.setObjectName(u"login_button")
        self.login_button.setMinimumSize(QSize(100, 50))
        font9 = QFont()
        font9.setFamilies([u"Gotham Pro Black"])
        font9.setPointSize(14)
        self.login_button.setFont(font9)
        self.login_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.login_button.setStyleSheet(u"background: #ffd17a;\n"
"border-radius: 5px;\n"
"")

        self.verticalLayout_3.addWidget(self.login_button)

        MainWindow.setCentralWidget(self.centralwidget)
        self.ibby_border.raise_()
        self.hyus_border.raise_()
        self.layoutWidget.raise_()
        self.wrap_button_2.raise_()
        self.wrap_button_3.raise_()
        self.start_button.raise_()
        self.menu.raise_()
        self.hyus_icon.raise_()
        self.pkle_border.raise_()
        self.ibby_icon.raise_()
        self.pkle_icon.raise_()
        self.wrewards_border.raise_()
        self.wrewards_icon.raise_()
        self.start_button_error_text.raise_()
        self.login_error_text.raise_()
        self.login_frame.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"VaynBot", None))
        self.wrap_button.setText("")
        self.close_button.setText("")
        self.start_button.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0430\u043b\u0435\u0435", None))
        self.wrap_button_2.setText("")
        self.wrap_button_3.setText("")
#if QT_CONFIG(tooltip)
        self.item_messages.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.item_messages.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f", None))
#if QT_CONFIG(tooltip)
        self.item_accounts.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.item_accounts.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0441\u0435 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u044b", None))
#if QT_CONFIG(tooltip)
        self.item_calendar.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.item_calendar.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0431\u043e\u0440 \u043a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u044f", None))
#if QT_CONFIG(tooltip)
        self.item_shop.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.item_shop.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0430\u0440\u0441\u0435\u0440 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u0430", None))
#if QT_CONFIG(tooltip)
        self.item_points.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.item_points.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u043e\u0432\u0435\u0440\u043a\u0430 \u043f\u043e\u0438\u043d\u0442\u043e\u0432", None))
#if QT_CONFIG(tooltip)
        self.item_devices.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.item_devices.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0440\u0443\u0433\u0438\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430", None))
        self.hyus_icon.setText("")
        self.pkle_border.setText("")
        self.hyus_border.setText("")
        self.ibby_icon.setText("")
        self.ibby_border.setText("")
        self.pkle_icon.setText("")
        self.wrewards_border.setText("")
        self.wrewards_icon.setText("")
        self.start_button_error_text.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0438\u0431\u0435\u0440\u0438\u0442\u0435 \u0441\u0442\u0440\u0438\u043c\u0435\u0440\u0430", None))
        self.login_error_text.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0435 \u0432\u0435\u0440\u043d\u044b\u0439 \u043b\u043e\u0433\u0438\u043d \u0438\u043b\u0438 \u043f\u0430\u0440\u043e\u043b\u044c.", None))
        self.login_label_title.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0445\u043e\u0434", None))
        self.pass_icon_2.setText("")
#if QT_CONFIG(statustip)
        self.login_title.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.login_title.setText(QCoreApplication.translate("MainWindow", u"\u041b\u043e\u0433\u0438\u043d", None))
        self.pass_icon.setText("")
        self.pass_title.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0430\u0440\u043e\u043b\u044c", None))
        self.forgot_pass.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u0431\u044b\u043b\u0438 \u043f\u0430\u0440\u043e\u043b\u044c?", None))
        self.label_space.setText("")
        self.login_button.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0430\u043b\u0435\u0435", None))
    # retranslateUi

